- pylintrc
- requirements.txt
- scraper.py
- scraper_test.py
Initial code to scrape mlab nodes.  Doesn't (yet) upload the data or interact with the spreadsheet, but enough code has been written that a review is a good idea.
> Scrape mlab nodes.

- .travis.yml
- scraper.py
- scraper_test.py
> Add tar support

- pre-commit
- prepare-commit-msg
- pylintrc
- scraper.py
- scraper_test.py
Added hooks to ensure unit tests and linters and formatters and code coverage always get run on every commit.
Cleaned up the code to minimize the resulting output.
> Hooks and cleanup

- README.md
- pre-commit
- pylintrc
- requirements.txt
- scraper.py
- scraper_test.py
Everything seems to work.  Check it out!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/4)
> Spreadsheet + Bucket upload

- AUTHORS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/5)
> Fixed a copy-and-past error in the AUTHORS file.

- Dockerfile
- scraper.py
- scraper_test.py
- test-requirements.txt
Our existing pipeline uncompresses all component files prior to archiving the data. This adds in code to do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/8)
> Uncompress component files of the tarfile prior to archiving.

- Dockerfile
- deploy.yml
- namspace.yml
A better dockerfile and the desired deployment template and the yml file to create the scraper namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/13)
> Adding .yml files and improving the Dockerfile

- scraper_test.py
- test-requirements.txt
This PR eliminates the log spam and garbage spewed to stderr from running the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/17)
> Test log spam elimination

- deploy.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/21)
> Unifying the template syntax for mlabconfig.py

- pre-commit
- prepare-commit-msg
- pylintrc
- scraper.py
- scraper_test.py
- sync/__init__.py
- sync/sync.py
- sync/sync_test.py
The first half of the sync client.  Downloads data from datastore, does not (yet) update the spreadsheet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/27)
> Datastore download

- pre-commit
- pylintrc
- run_scraper.py
- scraper.py
- sync/sync.py
- sync/sync_test.py
Sync the datastore data up to the spreadsheet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/29)
> A working spreadsheet and test coverage thereof!

- scraper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/31)
> Prevent datastore properties from getting too big

- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/32)
> Development with unit tests and responsibility :)

- .gitmodules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/35)
> Moved the git hooks to a separate repo

- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/36)
> Now "Synching 1000 files" will be more helpful

- run_scraper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/37)
> Max out sleep time at two hours

- .travis.yml
- run_scraper.py
- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/38)
> Removal of nocache and the gunzip foolishness

- README.md
- deploy.yml
- run_scraper.py
- scraper.py
- scraper_test.py
Also the start of some additions to the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/40)
> More instruments

- scraper.py
- scraper_test.py
Handle no data gracefully wrt mtime updating.
Also keep track of the per-chunk upload time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/41)
> Handle no data gracefully

- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/43)
> Keep files from the same test in the same tarfile.

- Dockerfile
- deploy.yml
Tightening in on the right values in deploy.yml and adding support for more args to the Dockerfile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/44)
> More args and less BS in the Dockerfile.

- k8s/deploy_template.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/48)
> Change the container name to just "scraper"

- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/49)
> Production deployment added.

- Dockerfile
- deploy.sh
- k8s/deploy_template.yml
- run_scraper.py
- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/50)
> Tarfiles on volumes

- deploy.sh
- scraper.py
- scraper_test.py
Small files should no longer break things
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/52)
> Many small files

- k8s/deploy_template.yml
- run_scraper.py
- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/53)
> Nuke existing tarfiles

- k8s/deploy_template.yml
- scraper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/54)
> Tiny bugfixes

- scraper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/55)
> Retry on HttpError

- README.md
- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/56)
> Deploy output

- scraper.py
- scraper_test.py
Disappearing ephemeral files can break the file listing operation as
well.  Don't let them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/61)
> rsync file list is more robust.

- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/63)
> Update regex for staging to exclude mlab4s at testing sites

- scraper.py
Don't add keys before we have corresponding values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/69)
> Zero values are not null values.

- Dockerfile
- deploy.sh
Use the pattern files to generate a deployment, and be compatible with Alpine Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/73)
> Pattern files and a rebuilt Docker image

- scraper.py
- scraper_test.py
Merging to staging before pushing to prod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/74)
> Update operator repo

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/76)
> Support auto deploy to mlab-oti

- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/78)
> Specify a key file for mlab-oti

- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/80)
> Stop kubernetes from timing out on deletes.

- deploy.sh
Even though, according to the docs, they mean the same thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/81)
> You can't use both --now and --grace-period=1

- deploy.sh
Submitting without review to debug Travis.
> Try to delete in the new, less-blocking way!

- deploy.sh
Bring them into staging to address Stephen's requests.
> Updated comments

- validation/verify-old-vs-new-june2017.sh
It is robust to subfiles being compressed in the new repo but not in the existing one.
The successful running of this script will help solve issue #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/106)
> A bash script to verify that we have the same data for June from both systems

- deploy.sh
Approval of this PR will cause a push to staging, eliminating prg01.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/156)
> Update list of sites

- run_scraper.py
- run_scraper_test.py
- scraper.py
- scraper_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/165)
> Upload eagerly when there is a lot of data.

- scraper.py
- scraper_test.py
Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/176)
> Eliminate the leading './' on filenames.

- run_scraper_test.py
- scraper.py
- scraper_test.py
Times should be monotonic now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/177)
> Repeated files bug

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/185)
> Update README.md to explain how tests are run.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/225)
> sleep to fix spurious failed tests and deployments

- .travis.yml
- deploy.sh
Also reverts the sleep from .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/226)
> Less output to stop making Travis sad.

- TestDockerfile
- prepare-commit-msg.sh
- run_tests_with_emulator.sh
Use the new improved git-hooks. Update all the submodules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/260)
> Updated repos

- scraper_test.py
Also updated the submodules.
The `@testfixtures.log_capture()` decorator became incompatible with `unittest` (thanks, guys). This removes our dependency on that decorator doing anything besides redirecting logging to `/dev/null`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/277)
> Now works with the latest test_fixtures library.

- requirements.txt
- run_scraper.py
- test-requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/319)
> Update submodules and fix travis failures

- run_scraper_test.py
This change adds extra information to the failing unit test to help us
debug these problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/320)
> Our unit tests on Travis are failing sometimes.

- deploy.sh
Reflect reality, and relieve quota pressure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/scraper/323)
> Remove mlab4's from scraper.
